### ISSUE TITLE
Internal server error using basic lambda

### ISSUE THREAD

**Issue by KorvinSzanto** [brefphp/constructs#12]
I have the following CDK code:
```ts
const apiLambda = new PhpFpmFunction(this, 'API Handler', {
  handler: 'index.php',
  code: packagePhpCode(path.join(__dirname, '../lambda/test'))
})

const api = new apigateway.RestApi(this, 'Upload API')
const uploadApiIntegration = new apigateway.LambdaIntegration(apiLambda);
api.root.addMethod('GET', uploadApiIntegration);
api.root.addMethod('POST', uploadApiIntegration);
```

which deploys fine:
![image](https://github.com/brefphp/constructs/assets/1007419/53b778a2-5525-4416-a4f6-202bd4ef85ae)
![image](https://github.com/brefphp/constructs/assets/1007419/46125b26-9ed9-4c4d-a332-602884adff47)

Yet when I try to invoke it either directly or through the created api gateway URL I get "Internal server error". For example, invoking it with `{}` gives:
```
Response
{
  "errorType": "Runtime.ExitError",
  "errorMessage": "RequestId: 27e2b321-f299-4dce-a4c7-ae0a59793c35 Error: Runtime exited with error: exit status 255"
}

Function Logs
INIT_REPORT Init Duration: 165.85 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
INIT_REPORT Init Duration: 285.10 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
START RequestId: 27e2b321-f299-4dce-a4c7-ae0a59793c35 Version: $LATEST
RequestId: 27e2b321-f299-4dce-a4c7-ae0a59793c35 Error: Runtime exited with error: exit status 255
Runtime.ExitError
END RequestId: 27e2b321-f299-4dce-a4c7-ae0a59793c35
REPORT RequestId: 27e2b321-f299-4dce-a4c7-ae0a59793c35	Duration: 286.64 ms	Billed Duration: 287 ms	Memory Size: 1024 MB	Max Memory Used: 25 MB
```

Any idea what I'm doing wrong?

**Comment by KorvinSzanto** [comment]
My issue was I didn't realize I needed the `bref/bref` vendor files. I assumed that since I don't need to include them in my index.php that they weren't needed but that's not the case.

**Comment by mnapoli** [comment]
That's weird, you should have gotten a more explicit error message:

https://github.com/brefphp/aws-lambda-layers/blob/main/layers/bootstrap.php#L14

Were you on the latest versions of the NPM packages?

**Comment by KorvinSzanto** [comment]
I was on the latest npm version. My test application didn't have a vendor at all so I think the require would fatal before that exception has a chance to throw. I can give it another try and see if there are more logs I was missing

**Comment by mnapoli** [comment]
Ohhh that's a good point! We could do a `file_exists` check for these edge cases 🤔

I wonder if it trips up many people
