### ISSUE TITLE
expose the created bucket ARN

### ISSUE THREAD

**Issue by zilahir** [brefphp/constructs#7]
Is there a way to get access to the created S3 Bucket's RN somehow? 

I would need it later in my `CDK` description. 

```typescript
const apiLambda = new PhpFpmFunction(this, `backend-${env}`, {
      handler: "public/index.php",
      code: packagePhpCode("../backend"),
      phpVersion: "8.2",
      timeout: Duration.seconds(30),
      environment: { // }
    });
```

this creates the `s3` bucket automatically in the cloudformation stack, and i'd need a way to get it's `ARN`. 

Any suggestion would be appreciated! 

UPDATE: I guess if it's possible to provide a custom s3 bucket also created in the stack that would work too.

**Comment by mnapoli** [comment]
What S3 bucket? I don't understand, it's a Lambda function, it's not deploying a S3 bucket 🤔

**Comment by leob** [comment]
@mnapoli Kudos for creating these CDK constructs, haven't tried it yet but a great initiative! I'd be eager/willing to contribute if only I had more knowledge about AWS and CDK ... :)

**Comment by mnapoli** [comment]
@leob thank you!
